FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

# Copy source code is not necessary here because of volume mount, 
# but good practice for consistency
COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]
